SELECT *
FROM tabela_de_clientes;

SELECT CPF as IDENTIFICADOR, NOME as CLIENTE FROM tabela_de_clientes;

SELECT *
FROM tabela_de_clientes
WHERE nome LIKE('%Mattos');

SELECT DISTINCT BAIRRO
FROM tabela_de_clientes
WHERE CIDADE = 'Rio de Janeiro'
LIMIT 2;

SELECT *
FROM notas_fiscais
WHERE DATA_VENDA = '2017-01-01'
LIMIT 10;

SELECT *
FROM itens_notas_fiscais
WHERE CODIGO_DO_PRODUTO = '1101035';

SELECT SUM(QUANTIDADE) as 'TOTAL DE VENDAS'
FROM itens_notas_fiscais
WHERE CODIGO_DO_PRODUTO = '1101035';

SELECT CODIGO_DO_PRODUTO, SUM(QUANTIDADE) as 'SOMA DE QNT'
FROM itens_notas_fiscais
GROUP BY CODIGO_DO_PRODUTO;

SELECT CPF, COUNT(*)
FROM notas_fiscais
WHERE YEAR(DATA_VENDA) = 2016
GROUP BY CPF
HAVING COUNT(*) > 2000;

SELECT NOME, DATA_DE_NASCIMENTO,
CASE
	WHEN YEAR(DATA_DE_NASCIMENTO) <= 1990 THEN 'VELHO'
    WHEN YEAR(DATA_DE_NASCIMENTO) > 1990 AND YEAR(DATA_DE_NASCIMENTO) <= 1995 THEN 'JOVEM'
    WHEN YEAR(DATA_DE_NASCIMENTO) > 1995 THEN 'CRIANÇA'
    ELSE 'NÃO TEM'
END AS 'STATUS'
FROM tabela_de_clientes
ORDER BY NOME desc;



